databases:
  - name: BlogApp
    databaseName: blogapp
    user: blogapp_user
    plan: free
services:
  - type: web
    name: BlogApp
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: BlogApp
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
    plan: free